project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - coral_survivorship_report.qmd
    - all_coral_cover.qmd
    - interactive_map.qmd

website:
  title: "DPNR Outplant Analyses"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: coral_survivorship_report.qmd
        text: Analysis Report
      - href: all_coral_cover.qmd
        text: All Coral Cover
      - href: interactive_map.qmd
        text: Interactive Map

format:
  html:
    theme:
      - cosmo
      - styles.scss
    include-after-body: site-labels.html
    toc: true
    code-fold: true
    embed-resources: false
    fig-format: svg

knitr:
  opts_chunk:
    dev: "svglite"
